vim.opt.backup = false,                                  -- Backup file creation
vim.opt.clipboard = "unnamedplus",                       -- Permit system clipboard access 
vim.opt.cmdheight = 2,                                   -- Command line spacing 
vim.opt.completeopt = {"menuone", "noselect"},           -- Popup menu, do not select one by default force user to select one
vim.opt.pumheight = 5,                                   -- Max number of items to be shown in the popup menu     
vim.opt.conceallevel = 0,                                -- Syntax highliting, show normally 
vim.opt.filencoding = "utf-8",                           -- Encoding written to a file 
vim.opt.hlsearch = true,                                 -- Highlight matches on search
vim.opt.ignorecase = true,                               -- Disable case sensitivity in search patterns 
vim.opt.mouse = "a",                                     -- Enable mouse to be used in all modes
vim.opt.showmode = false,                                -- Hide vim mode 
vim.opt.showtabline = 2,                                 -- Show tabs 
vim.opt.smartcase = true,                                -- Enable smart case
vim.opt.smartindent = true,                              -- Enable smart indent 
vim.opt.splitbelow = true,                               -- Force split down from current window
vim.opt.splitright = true,                               -- Force split right from current window
vim.opt.swapfile = false,                                -- Disable swap file creation
vim.opt.timeoutlen = 1000,                               -- Wait time of a map sequence completion 
vim.opt.undofile = true,                                 -- Enable persistent undo
vim.opt.updatetime = 300,                                -- Millisecond window in which the swap file is written to disk 
vim.opt.writebackup = false,                             -- Do not allow file editing when open by another program
vim.opt.expandtab = true,                                -- Allow tabs to spaces conversion
vim.opt.shiftwidth = 2,                                  -- Number of spaces to be inserted for each indent  
vim.opt.tabstop = 4,                                     -- Spaces to insert for a tab
vim.opt.cursorline = true,                               -- Enable highlighting for the cursor line 
vim.opt.number = true,                                   -- Enable numbered lines
vim.opt.relativenumber = true,                           -- Show line numbers relative to line cursor
vim.opt.numberwidth = 4,                                 -- Columns to be used for the numbered line 
vim.opt.signcolumn = "yes",                              -- Always draw the sign column 
vim.opt.wrap = "false",                                  -- Do not wrap around lines
vim.opt.scrolloff = 8,                                   -- Min number of screen lines to keep above and below the cursor
vim.opt.sidescrolloff = 8,                               -- Min number of columns to keep to the left and right of the cursor
vim.opt.guifont = "monospace:h17",                       -- Font for the graphical user interface
vim.opt.shell = "C:\\Program Files\\Git\\git-bash.exe",  -- Shell to be used for ! commands and :! commands
vim.opt.shortmess:append "c",                            -- Avoid instacompletion messages from popup menu

vim.cmd "set whichwrap+=<,>,[,],h,l"
vim.cmd [[set iskeyword+=-]]
vim.cmd [[set formatoptions-=cro]]
